# This workflow will install Python and Node dependencies, run tests and lint with a variety of Python and Node versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: fp-ts-learning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  node-api-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    # Use this step to debug container with tmate
    # - name: Setup tmate session
      # uses: mxschmitt/action-tmate@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run lint and tests
      run: |
        npm install && npm test
